kind: pipeline
type: docker
name: default

steps:
- name: terraform-lint
  image: hashicorp/terraform:1.5.0
  when:
    branch: main
  commands:
    - "terraform fmt -diff -check -recursive"

- name: terraform-init
  image: hashicorp/terraform:1.5.0
  when:
    branch: main
  commands:
    - "terraform init"

- name: terraform-plan
  image: hashicorp/terraform:1.5.0
  secrets: [ metal_auth_token, project_name ]
  environment:
    METAL_AUTH_TOKEN:
      from_secret: metal_auth_token
    TF_VAR_project_name:
      from_secret: project_name
    X-Auth-Token:
      from_secret: metal_auth_token
  when:
    branch: main
  commands:
    - "terraform plan"
---
kind: signature
hmac: 91759c0619998b25b3a5844f9f268d84f9a662336bec063713936d39c6e7bdb5
